//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CHECKLIST", Namespace="http://schemas.datacontract.org/2004/07/Masco.Display.ILSValidator.Entities")]
    [System.SerializableAttribute()]
    public partial class CHECKLIST : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPLY_AMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPLY_OBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APPLY_OEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BOTTOM_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHECKLIST_PKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CREATE_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ILS_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IS_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAIN_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MAP_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MMS_LONLATField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NODE_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REQ_TYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REQ_UNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UPDATE_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPDATE_UNAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WORK_STATEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPLY_AM {
            get {
                return this.APPLY_AMField;
            }
            set {
                if ((object.ReferenceEquals(this.APPLY_AMField, value) != true)) {
                    this.APPLY_AMField = value;
                    this.RaisePropertyChanged("APPLY_AM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPLY_OBN {
            get {
                return this.APPLY_OBNField;
            }
            set {
                if ((object.ReferenceEquals(this.APPLY_OBNField, value) != true)) {
                    this.APPLY_OBNField = value;
                    this.RaisePropertyChanged("APPLY_OBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APPLY_OEM {
            get {
                return this.APPLY_OEMField;
            }
            set {
                if ((object.ReferenceEquals(this.APPLY_OEMField, value) != true)) {
                    this.APPLY_OEMField = value;
                    this.RaisePropertyChanged("APPLY_OEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BOTTOM_NAME {
            get {
                return this.BOTTOM_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.BOTTOM_NAMEField, value) != true)) {
                    this.BOTTOM_NAMEField = value;
                    this.RaisePropertyChanged("BOTTOM_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHECKLIST_PK {
            get {
                return this.CHECKLIST_PKField;
            }
            set {
                if ((this.CHECKLIST_PKField.Equals(value) != true)) {
                    this.CHECKLIST_PKField = value;
                    this.RaisePropertyChanged("CHECKLIST_PK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CREATE_DT {
            get {
                return this.CREATE_DTField;
            }
            set {
                if ((this.CREATE_DTField.Equals(value) != true)) {
                    this.CREATE_DTField = value;
                    this.RaisePropertyChanged("CREATE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ILS_TYPE {
            get {
                return this.ILS_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.ILS_TYPEField, value) != true)) {
                    this.ILS_TYPEField = value;
                    this.RaisePropertyChanged("ILS_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IS_NAME {
            get {
                return this.IS_NAMEField;
            }
            set {
                if ((this.IS_NAMEField.Equals(value) != true)) {
                    this.IS_NAMEField = value;
                    this.RaisePropertyChanged("IS_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAIN_CODE {
            get {
                return this.MAIN_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.MAIN_CODEField, value) != true)) {
                    this.MAIN_CODEField = value;
                    this.RaisePropertyChanged("MAIN_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MAP_ID {
            get {
                return this.MAP_IDField;
            }
            set {
                if ((this.MAP_IDField.Equals(value) != true)) {
                    this.MAP_IDField = value;
                    this.RaisePropertyChanged("MAP_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MMS_LONLAT {
            get {
                return this.MMS_LONLATField;
            }
            set {
                if ((object.ReferenceEquals(this.MMS_LONLATField, value) != true)) {
                    this.MMS_LONLATField = value;
                    this.RaisePropertyChanged("MMS_LONLAT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NAME {
            get {
                return this.NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.NAMEField, value) != true)) {
                    this.NAMEField = value;
                    this.RaisePropertyChanged("NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NODE_ID {
            get {
                return this.NODE_IDField;
            }
            set {
                if ((this.NODE_IDField.Equals(value) != true)) {
                    this.NODE_IDField = value;
                    this.RaisePropertyChanged("NODE_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REQ_TYPE {
            get {
                return this.REQ_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.REQ_TYPEField, value) != true)) {
                    this.REQ_TYPEField = value;
                    this.RaisePropertyChanged("REQ_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REQ_UNAME {
            get {
                return this.REQ_UNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.REQ_UNAMEField, value) != true)) {
                    this.REQ_UNAMEField = value;
                    this.RaisePropertyChanged("REQ_UNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UPDATE_DT {
            get {
                return this.UPDATE_DTField;
            }
            set {
                if ((this.UPDATE_DTField.Equals(value) != true)) {
                    this.UPDATE_DTField = value;
                    this.RaisePropertyChanged("UPDATE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UPDATE_UNAME {
            get {
                return this.UPDATE_UNAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.UPDATE_UNAMEField, value) != true)) {
                    this.UPDATE_UNAMEField = value;
                    this.RaisePropertyChanged("UPDATE_UNAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WORK_STATE {
            get {
                return this.WORK_STATEField;
            }
            set {
                if ((object.ReferenceEquals(this.WORK_STATEField, value) != true)) {
                    this.WORK_STATEField = value;
                    this.RaisePropertyChanged("WORK_STATE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LANEINFO", Namespace="http://schemas.datacontract.org/2004/07/Masco.Display.ILSValidator.Entities")]
    [System.SerializableAttribute()]
    public partial class LANEINFO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHECKLIST_PKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CREATE_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DIRECTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMAGE_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMAGE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IS_DELETEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LANEINFO_PKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LANE_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NUMBERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UPDATE_DTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHECKLIST_PK {
            get {
                return this.CHECKLIST_PKField;
            }
            set {
                if ((this.CHECKLIST_PKField.Equals(value) != true)) {
                    this.CHECKLIST_PKField = value;
                    this.RaisePropertyChanged("CHECKLIST_PK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CREATE_DT {
            get {
                return this.CREATE_DTField;
            }
            set {
                if ((this.CREATE_DTField.Equals(value) != true)) {
                    this.CREATE_DTField = value;
                    this.RaisePropertyChanged("CREATE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DIRECTION {
            get {
                return this.DIRECTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DIRECTIONField, value) != true)) {
                    this.DIRECTIONField = value;
                    this.RaisePropertyChanged("DIRECTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAGE_CODE {
            get {
                return this.IMAGE_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGE_CODEField, value) != true)) {
                    this.IMAGE_CODEField = value;
                    this.RaisePropertyChanged("IMAGE_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAGE_NAME {
            get {
                return this.IMAGE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGE_NAMEField, value) != true)) {
                    this.IMAGE_NAMEField = value;
                    this.RaisePropertyChanged("IMAGE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IS_DELETE {
            get {
                return this.IS_DELETEField;
            }
            set {
                if ((this.IS_DELETEField.Equals(value) != true)) {
                    this.IS_DELETEField = value;
                    this.RaisePropertyChanged("IS_DELETE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LANEINFO_PK {
            get {
                return this.LANEINFO_PKField;
            }
            set {
                if ((this.LANEINFO_PKField.Equals(value) != true)) {
                    this.LANEINFO_PKField = value;
                    this.RaisePropertyChanged("LANEINFO_PK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LANE_NAME {
            get {
                return this.LANE_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.LANE_NAMEField, value) != true)) {
                    this.LANE_NAMEField = value;
                    this.RaisePropertyChanged("LANE_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NUMBER {
            get {
                return this.NUMBERField;
            }
            set {
                if ((this.NUMBERField.Equals(value) != true)) {
                    this.NUMBERField = value;
                    this.RaisePropertyChanged("NUMBER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UPDATE_DT {
            get {
                return this.UPDATE_DTField;
            }
            set {
                if ((this.UPDATE_DTField.Equals(value) != true)) {
                    this.UPDATE_DTField = value;
                    this.RaisePropertyChanged("UPDATE_DT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="REQUEST", Namespace="http://schemas.datacontract.org/2004/07/Masco.Display.ILSValidator.Entities")]
    [System.SerializableAttribute()]
    public partial class REQUEST : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CHECKLIST_PKField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CREATE_DTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPTIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IS_DELETEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string REQ_KINDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime UPDATE_DTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CHECKLIST_PK {
            get {
                return this.CHECKLIST_PKField;
            }
            set {
                if ((this.CHECKLIST_PKField.Equals(value) != true)) {
                    this.CHECKLIST_PKField = value;
                    this.RaisePropertyChanged("CHECKLIST_PK");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CREATE_DT {
            get {
                return this.CREATE_DTField;
            }
            set {
                if ((this.CREATE_DTField.Equals(value) != true)) {
                    this.CREATE_DTField = value;
                    this.RaisePropertyChanged("CREATE_DT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPTION {
            get {
                return this.DESCRIPTIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPTIONField, value) != true)) {
                    this.DESCRIPTIONField = value;
                    this.RaisePropertyChanged("DESCRIPTION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDX {
            get {
                return this.IDXField;
            }
            set {
                if ((this.IDXField.Equals(value) != true)) {
                    this.IDXField = value;
                    this.RaisePropertyChanged("IDX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IS_DELETE {
            get {
                return this.IS_DELETEField;
            }
            set {
                if ((this.IS_DELETEField.Equals(value) != true)) {
                    this.IS_DELETEField = value;
                    this.RaisePropertyChanged("IS_DELETE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string REQ_KIND {
            get {
                return this.REQ_KINDField;
            }
            set {
                if ((object.ReferenceEquals(this.REQ_KINDField, value) != true)) {
                    this.REQ_KINDField = value;
                    this.RaisePropertyChanged("REQ_KIND");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime UPDATE_DT {
            get {
                return this.UPDATE_DTField;
            }
            set {
                if ((this.UPDATE_DTField.Equals(value) != true)) {
                    this.UPDATE_DTField = value;
                    this.RaisePropertyChanged("UPDATE_DT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USER", Namespace="http://schemas.datacontract.org/2004/07/Masco.Display.ILSValidator.Entities")]
    [System.SerializableAttribute()]
    public partial class USER : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ETCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USER_PKField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETC {
            get {
                return this.ETCField;
            }
            set {
                if ((object.ReferenceEquals(this.ETCField, value) != true)) {
                    this.ETCField = value;
                    this.RaisePropertyChanged("ETC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_IDField, value) != true)) {
                    this.USER_IDField = value;
                    this.RaisePropertyChanged("USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_PASSWORD {
            get {
                return this.USER_PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_PASSWORDField, value) != true)) {
                    this.USER_PASSWORDField = value;
                    this.RaisePropertyChanged("USER_PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USER_PK {
            get {
                return this.USER_PKField;
            }
            set {
                if ((this.USER_PKField.Equals(value) != true)) {
                    this.USER_PKField = value;
                    this.RaisePropertyChanged("USER_PK");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.masco.co.kr/ILSValidator", ConfigurationName="ServiceReferenceCheckList.ICheckList")]
    public interface ICheckList {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/Validate", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/ValidateResponse")]
        bool Validate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/GetCheckList", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/GetCheckListResponse")]
        Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST[] GetCheckList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/GetCheckListBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/GetCheckListByResponse")]
        Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST[] GetCheckListBy(System.Collections.Generic.Dictionary<string, string> filter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/InsertCheckList", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/InsertCheckListResponse")]
        int InsertCheckList(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateCheckList", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateCheckListResponse")]
        int UpdateCheckList(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/GetImagePkBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/GetImagePkByResponse")]
        int GetImagePkBy(int checkListPk, bool isBasemap);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateImageIsUse", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateImageIsUseResponse")]
        int UpdateImageIsUse(int imagePk, bool isUse);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/GetMemoBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/GetMemoByResponse")]
        string GetMemoBy(int checkListPk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/InsertMemo", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/InsertMemoResponse")]
        int InsertMemo(int checkListPk, string remarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/GetLaneInfoListBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/GetLaneInfoListByResponse")]
        Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.LANEINFO[] GetLaneInfoListBy(int checkListPk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/InsertLaneInfo", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/InsertLaneInfoResponse")]
        int InsertLaneInfo(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.LANEINFO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateLaneInfo", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateLaneInfoResponse")]
        int UpdateLaneInfo(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.LANEINFO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/DeleteLaneInfoBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/DeleteLaneInfoByResponse")]
        int DeleteLaneInfoBy(int laneInfoPk);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/GetRequestListBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/GetRequestListByResponse")]
        Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST[] GetRequestListBy(int checklistPk, string reqType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/GetRequestBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/GetRequestByResponse")]
        Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST GetRequestBy(int checklistPk, int idx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/DeleteRequestBy", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/DeleteRequestByResponse")]
        int DeleteRequestBy(int checklistPk, int idx);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/InsertRequest", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/InsertRequestResponse")]
        int InsertRequest(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateRequest", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/UpdateRequestResponse")]
        int UpdateRequest(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.masco.co.kr/ILSValidator/ICheckList/UserCheck", ReplyAction="http://www.masco.co.kr/ILSValidator/ICheckList/UserCheckResponse")]
        bool UserCheck(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.USER user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICheckListChannel : Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.ICheckList, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckListClient : System.ServiceModel.ClientBase<Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.ICheckList>, Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.ICheckList {
        
        public CheckListClient() {
        }
        
        public CheckListClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CheckListClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckListClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CheckListClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Validate() {
            return base.Channel.Validate();
        }
        
        public Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST[] GetCheckList() {
            return base.Channel.GetCheckList();
        }
        
        public Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST[] GetCheckListBy(System.Collections.Generic.Dictionary<string, string> filter) {
            return base.Channel.GetCheckListBy(filter);
        }
        
        public int InsertCheckList(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST entity) {
            return base.Channel.InsertCheckList(entity);
        }
        
        public int UpdateCheckList(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.CHECKLIST entity) {
            return base.Channel.UpdateCheckList(entity);
        }
        
        public int GetImagePkBy(int checkListPk, bool isBasemap) {
            return base.Channel.GetImagePkBy(checkListPk, isBasemap);
        }
        
        public int UpdateImageIsUse(int imagePk, bool isUse) {
            return base.Channel.UpdateImageIsUse(imagePk, isUse);
        }
        
        public string GetMemoBy(int checkListPk) {
            return base.Channel.GetMemoBy(checkListPk);
        }
        
        public int InsertMemo(int checkListPk, string remarks) {
            return base.Channel.InsertMemo(checkListPk, remarks);
        }
        
        public Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.LANEINFO[] GetLaneInfoListBy(int checkListPk) {
            return base.Channel.GetLaneInfoListBy(checkListPk);
        }
        
        public int InsertLaneInfo(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.LANEINFO entity) {
            return base.Channel.InsertLaneInfo(entity);
        }
        
        public int UpdateLaneInfo(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.LANEINFO entity) {
            return base.Channel.UpdateLaneInfo(entity);
        }
        
        public int DeleteLaneInfoBy(int laneInfoPk) {
            return base.Channel.DeleteLaneInfoBy(laneInfoPk);
        }
        
        public Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST[] GetRequestListBy(int checklistPk, string reqType) {
            return base.Channel.GetRequestListBy(checklistPk, reqType);
        }
        
        public Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST GetRequestBy(int checklistPk, int idx) {
            return base.Channel.GetRequestBy(checklistPk, idx);
        }
        
        public int DeleteRequestBy(int checklistPk, int idx) {
            return base.Channel.DeleteRequestBy(checklistPk, idx);
        }
        
        public int InsertRequest(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST entity) {
            return base.Channel.InsertRequest(entity);
        }
        
        public int UpdateRequest(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.REQUEST entity) {
            return base.Channel.UpdateRequest(entity);
        }
        
        public bool UserCheck(Masco.Display.ILSValidator.Client.Common.ServiceReferenceCheckList.USER user) {
            return base.Channel.UserCheck(user);
        }
    }
}
